name: fbref daily data

on:
  schedule:
    # Runs every day
    # - cron: '0 0 * * *'

    # Run every Monday
    - cron: '0 0 * * MON'

env:
  token: ${{ secrets.SECRET_TOKEN }}

jobs:
  daily-update-full-data:
    runs-on: ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          token: ${{ secrets.SECRET_TOKEN }}
      # Step 2: Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Install the Python version needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pandas
            pip install openpyxl
            pip install lxml

      # Step 4: Execute the Python script to update full data
      - name: Generate full data
        run: python src/fbref_scrap.py

      # Step 8: Commit and push the generated full data file if there are changes
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -a -m "Update full data"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SECRET_TOKEN }}
          branch: ${{ github.ref }}
          directory: .
          force: true
      